name: PixelProps

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: "Device Name"
        required: true
        default: "husky"
        type: choice
 
        options:
          - shiba
          - husky
          - cheetah
          - panther
          - oriole
          - raven
          - barbet
          - redfin
          - bramble
          - sunfish
          - coral
          - flame
          - bonito
          - sailfish

jobs:
  build:
    name: Build Props
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Clone Repo PixelPropsModule
        uses: whyakari/github-repo-action@v3.1
        with:
          branch: 'main'
          owner: 'whyakari'
          repository: 'PixelPropsModule'

      - name: Install dos2unix python3 python3-pip
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: dos2unix python3 python3-pip

      - name: Install protobuf
        working-directory: ./PixelPropsModule
        run: |
          pip install --upgrade pip
          pip3 install -Iv protobuf==3.20.3

      - name: Make executable all script
        working-directory: ./PixelPropsModule
        run: |
          chmod +x *.sh

      - name: Download last ota ${{ github.event.inputs.device_name }}
        working-directory: ./PixelPropsModule
        run: |
          ./download_last_ota_build.sh ${{ github.event.inputs.device_name }}

      - name: Extract Image and build Prop
        working-directory: ./PixelPropsModule
        run: |
          ./extract_images.sh

      - name: Read final_name from file
        id: read_name
        run: | 
          echo "final_name=$(cat build.txt)" >> $GITHUB_OUTPUT
        working-directory: ./PixelPropsModule

      - name: Copy prop to result ${{ matrix.device_name }}
        working-directory: ./PixelPropsModule
        run: |
          mkdir -p result
          cp ./**/**/{system,module}.prop result/
          cp -r META-INF/ result/
          cp customize.sh result/
          zip -r ${{ steps.read_name.final_name }}.zip result/*

      - name: Debug
        working-directory: ./PixelPropsModule
        run: |
          export zipname=$(find . -type f -name '*Pixel*.zip' -print -quit)
          echo $zipname
  
      - name: Search archive zip
        id: find-zip
        working-directory: ./PixelPropsModule
        run: |
          echo "zipname=$(find . -type f -name '*Pixel*.zip' -print -quit)" >> $GITHUB_ENV
          
      - name: Upload PixelProps to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/PixelPropsModule/PixelPropsModule/PixelPropsModule/${{ steps.read_name.outputs.final_name }}.zip               
          token: ${{ secrets.TOKEN_GITHUB }}
          name: "PixelProps Update"
          tag_name: ${{ steps.read_name.outputs.final_name }}
          body_path: changelog.md
