name: PixelProps (schedule)

on:
  workflow_dispatch:
  schedule:
    - cron: "37 13 7 * *" # At 13:37 on day-of-month 7. (UTC)

jobs:
  onSchedule:
    name: On Schedule
    strategy:
      matrix:
        device_name: [redfin, husky, shiba, cheetah, raven]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install dos2unix python3 python3-pip
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: dos2unix python3 python3-pip

      - name: Install protobuf
        run: |
          pip install --upgrade pip
          pip3 install -Iv protobuf==3.20.3

      - name: Make executable all script
        run: chmod +x *.sh

      - name: Download last ota ${{ matrix.device_name }}
        run: ./download_last_ota_build.sh ${{ matrix.device_name }}

      - name: Extract Image and build prop ${{ matrix.device_name }}
        run: ./extract_images.sh

      - name: Cat build.txt
        id: read_name
        run: |
          echo "final_name=$(cat build.txt)" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}

      - name: Copy prop to result ${{ matrix.device_name }}
        run: |
          mkdir -p result
          cp ./**/**/{system,module}.prop result/
          cp -r META-INF/ result/
          cp customize.sh result/

      - name: Upload Prop ${{ matrix.device_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.read_name.outputs.final_name }}
          path: result
          if-no-files-found: error
